name: SimplyHeightLimit
description: Limit Fly Height.
version: @version@
main: net.simplyvanilla.simplyheightlimit.SimplyHeightLimit
api-version: 1.18

author: Simply Vanilla
website: https://github.com/SimplyVanilla/SimplyHeightLimit
